apiVersion: deviceregistry.microsoft.com/v1
kind: Asset
metadata:
  name: spaceship-assembly-line-1
  namespace: azure-iot-operations
spec:
  assetEndpointProfileRef: spaceship-factory-mqtt
  uuid: spaceship-assembly-line-1
  displayName: "Spaceship Assembly Line 1"
  description: "Main assembly line for spaceship manufacturing"
  manufacturer: "SpaceShip Factory"
  model: "Assembly-Line-v1"
  productCode: "ASL-001"
  hardwareRevision: "1.0"
  softwareRevision: "2.1.0"
  documentationUri: "https://github.com/BillmanH/learn-iot"
  serialNumber: "ASL-001-2024"
  defaultTopic: "factory/assembly-line-1"
  defaultDataSource: 
    name: "SpaceShip Factory MQTT"
    observabilityMode: "None"
  dataPoints:
  - name: temperature
    dataSource: "factory/assembly-line-1/telemetry"
    observabilityMode: "None"
    dataPointConfiguration: |
      {
        "mqttPath": "temperature",
        "schema": "double"
      }
  - name: pressure
    dataSource: "factory/assembly-line-1/telemetry"
    observabilityMode: "None"
    dataPointConfiguration: |
      {
        "mqttPath": "pressure",
        "schema": "double"
      }
  - name: production_count
    dataSource: "factory/assembly-line-1/telemetry"
    observabilityMode: "None"
    dataPointConfiguration: |
      {
        "mqttPath": "production_count",
        "schema": "integer"
      }
  - name: status
    dataSource: "factory/assembly-line-1/telemetry"
    observabilityMode: "None"
    dataPointConfiguration: |
      {
        "mqttPath": "status",
        "schema": "string"
      }
