apiVersion: deviceregistry.microsoft.com/v1
kind: AssetEndpointProfile
metadata:
  name: spaceship-factory-opcua
  namespace: azure-iot-operations
spec:
  uuid: spaceship-factory-opcua-endpoint
  targetAddress: "opc.tcp://opc-plc-service.azure-iot-operations.svc.cluster.local:50000"
  endpointProfileType: Microsoft.AssetEndpointProfile/opcua/1.0.0
  authentication:
    method: Anonymous
  additionalConfiguration: |
    {
      "applicationName": "SpaceShip Factory OPC UA Connector",
      "securityPolicy": "None",
      "securityMode": "None",
      "sessionTimeout": 60000,
      "sessionKeepAliveInterval": 10000
    }