apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: <YOUR_REGISTRY>/hello-flask:latest
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080  # Accessible on <edge-device-ip>:30080
