apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: BrokerAuthorization
metadata:
  name: edge-apps-authz
  namespace: azure-iot-operations
spec:
  authorizationPolicies:
    cache: Enabled
    rules:
      - principals:
          attributes:
            - group: "edge-apps"
        brokerResources:
          - method: Connect
          - method: Publish
            topics:
              - "factory/#"
              - "historian/#"
              - "telemetry/#"
          - method: Subscribe
            topics:
              - "factory/#"
              - "commands/#"
              - "config/#"
      - principals:
          attributes:
            - group: "connectors"
        brokerResources:
          - method: Connect
          - method: Publish
            topics:
              - "historian/#"
              - "factory/#"
              - "#"
          - method: Subscribe
            topics:
              - "akri/#"
