apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: factory-cnc-to-fabric
  namespace: azure-iot-operations
spec:
  profileRef: default
  mode: Enabled
  
  operations:
    # Source: Only CNC machine topics
    - operationType: Source
      name: cnc-source
      sourceSettings:
        endpointRef: default
        dataSources:
          - "factory/cnc/#"  # All CNC machine messages
    
    # Optional: Transform to add metadata
    - operationType: Transform
      name: add-machine-type
      transformSettings:
        serializationFormat: Json
        datasets:
          - key: ".metadata.machine_type"
            value: "CNC"
          - key: ".metadata.source"
            value: "factory-mqtt"
    
    # Destination: Fabric RTI
    - operationType: Destination
      name: fabric-destination
      destinationSettings:
        endpointRef: fabric-realtime
        dataDestination: "es_YOUR_FABRIC_TOPIC_ID"  # Replace with actual topic

---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: factory-3dprinter-to-fabric
  namespace: azure-iot-operations
spec:
  profileRef: default
  mode: Enabled
  
  operations:
    # Source: Only 3D printer topics
    - operationType: Source
      name: printer-source
      sourceSettings:
        endpointRef: default
        dataSources:
          - "factory/3dprinter/#"  # All 3D printer messages
    
    # Transform: Add machine type metadata
    - operationType: Transform
      name: add-machine-type
      transformSettings:
        serializationFormat: Json
        datasets:
          - key: ".metadata.machine_type"
            value: "3DPrinter"
          - key: ".metadata.source"
            value: "factory-mqtt"
    
    # Destination: Fabric RTI
    - operationType: Destination
      name: fabric-destination
      destinationSettings:
        endpointRef: fabric-realtime
        dataDestination: "es_YOUR_FABRIC_TOPIC_ID"  # Replace with actual topic

---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: factory-welding-to-fabric
  namespace: azure-iot-operations
spec:
  profileRef: default
  mode: Enabled
  
  operations:
    # Source: Only welding station topics
    - operationType: Source
      name: welding-source
      sourceSettings:
        endpointRef: default
        dataSources:
          - "factory/welding/#"
    
    # Transform: Add machine type
    - operationType: Transform
      name: add-machine-type
      transformSettings:
        serializationFormat: Json
        datasets:
          - key: ".metadata.machine_type"
            value: "Welding"
          - key: ".metadata.source"
            value: "factory-mqtt"
    
    # Destination: Fabric RTI
    - operationType: Destination
      name: fabric-destination
      destinationSettings:
        endpointRef: fabric-realtime
        dataDestination: "es_YOUR_FABRIC_TOPIC_ID"

---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: factory-critical-only
  namespace: azure-iot-operations
spec:
  profileRef: default
  mode: Enabled
  
  operations:
    # Source: All factory topics
    - operationType: Source
      name: factory-source
      sourceSettings:
        endpointRef: default
        dataSources:
          - "factory/#"
    
    # Transform: Filter for critical conditions only
    # This uses JQ-style filtering
    - operationType: Transform
      name: filter-critical
      transformSettings:
        serializationFormat: Json
        # Filter conditions - only pass messages where:
        # - Temperature > 80 OR
        # - Status == "error" OR "maintenance"
        filter:
          - inputs:
              - "*"  # All fields
            expression: |
              .payload.temperature > 80 or 
              .payload.status == "error" or 
              .payload.status == "maintenance"
        
        # Add alert metadata
        datasets:
          - key: ".metadata.alert_type"
            value: "critical"
          - key: ".metadata.priority"
            value: "high"
    
    # Destination: Fabric RTI (could be different Eventstream)
    - operationType: Destination
      name: fabric-destination
      destinationSettings:
        endpointRef: fabric-realtime
        dataDestination: "es_YOUR_FABRIC_ALERTS_TOPIC"  # Separate topic for alerts

---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: factory-aggregated
  namespace: azure-iot-operations
spec:
  profileRef: default
  mode: Enabled
  
  operations:
    # Source: All factory machines
    - operationType: Source
      name: factory-all-source
      sourceSettings:
        endpointRef: default
        dataSources:
          - "factory/cnc/#"
          - "factory/3dprinter/#"
          - "factory/welding/#"
          - "factory/painting/#"
          - "factory/testing/#"
    
    # Transform: Enrich with asset metadata
    - operationType: Transform
      name: enrich-data
      transformSettings:
        serializationFormat: Json
        datasets:
          - key: ".metadata.asset_id"
            value: "factory-mqtt-asset"
          - key: ".metadata.location"
            value: "eastus"
          - key: ".metadata.cluster"
            value: "bel-aio-work-cluster"
          - key: ".metadata.timestamp"
            expression: "now()"
    
    # Destination: All data to Fabric
    - operationType: Destination
      name: fabric-destination
      destinationSettings:
        endpointRef: fabric-realtime
        dataDestination: "es_YOUR_FABRIC_TOPIC_ID"
