apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowEndpoint
metadata:
  name: fabric-realtime
  namespace: azure-iot-operations
spec:
  endpointType: Kafka
  kafkaSettings:
    # Bootstrap server from Fabric Event Stream custom endpoint
    # Format: <your-eventhub>.servicebus.windows.net:9093
    # REPLACE THIS with your actual bootstrap server
    host: "YOUR_FABRIC_EVENTHUB.servicebus.windows.net:9093"
    
    # TLS must be enabled for Fabric connection
    tls:
      mode: Enabled
    
    # SASL authentication using connection string
    authentication:
      method: Sasl
      saslSettings:
        saslType: Plain
        # Reference to the Kubernetes secret containing the connection string
        secretRef: fabric-realtime-secret
    
    # Kafka settings
    consumerGroupId: iot-operations-consumer
    compression: None
    
    # Copy MQTT properties to Kafka headers
    copyMqttProperties: Enabled
    
    # CloudEvents format (optional)
    cloudEventAttributes: Propagate

---
# Kubernetes Secret for SASL Authentication
# This is a template - you should create this using kubectl create secret
# 
# kubectl create secret generic fabric-realtime-secret \
#   -n azure-iot-operations \
#   --from-literal=username='$ConnectionString' \
#   --from-literal=password='<YOUR_CONNECTION_STRING_FROM_FABRIC>'
#
# The username MUST be exactly: $ConnectionString
# The password is the full connection string from Fabric Event Stream
