apiVersion: v1
kind: Pod
metadata:
  name: mqtt-debug-client
  namespace: azure-iot-operations
spec:
  serviceAccountName: mqtt-client
  containers:
  - name: mqtt-client
    image: eclipse-mosquitto:2.0
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    env:
    - name: MQTT_BROKER
      value: "aio-broker.azure-iot-operations.svc.cluster.local"
    - name: MQTT_PORT
      value: "18883"
    volumeMounts:
    - name: broker-sat
      mountPath: /var/run/secrets/tokens
      readOnly: true
  volumes:
  - name: broker-sat
    projected:
      sources:
      - serviceAccountToken:
          path: broker-sat
          audience: aio-internal
          expirationSeconds: 86400
