# ==============================================================================
# Check-Permissions.ps1 - Pre-flight permission check for AIO deployment
#
# USAGE:
#   cd azd-deploy
#   .\Check-Permissions.ps1
#
# Checks that the signed-in user has exactly the rights required by main.bicep
# before running .\Deploy.ps1.  Exits 1 with fix instructions if any check
# fails.  Exits 0 only when everything looks good.
#
# Required roles (least privilege) — both must be held at sub or RG scope:
#   Contributor                       - create VNet, VM, KV, Storage, ACR, Schema Registry
#   Role Based Access Control Admin   - write the 4 role assignments in roleAssignments.bicep:
#       Key Vault Secrets User        -> AIO managed identity  (on Key Vault)
#       Key Vault Secrets Officer     -> deploying user         (on Key Vault)
#       Storage Blob Data Contributor -> schema registry        (on Storage)
#       AcrPull                       -> VM system identity     (on Container Registry)
#
# "Owner" (which includes both) is also accepted.
#
# Checks performed:
#   1. az login is active and subscription is accessible
#   2. Deployer has Contributor or Owner at sub or RG scope
#   3. Deployer has Role Based Access Control Administrator or Owner at sub or RG scope
#   4. No soft-deleted Key Vault with the same env-name prefix exists
# ==============================================================================

$ErrorActionPreference = 'Stop'

# Built-in role IDs the deployer themselves must hold
$OwnerId     = '8e3af657-a8ff-443c-a75c-2fe8c4bcb635'  # Owner (covers both below)
$ContribId   = 'b24988ac-6180-42a0-ab88-20f7382dd24c'  # Contributor
$RbacAdminId = 'f58310d9-a9f6-439a-9e8d-f62e7b41a168'  # Role Based Access Control Administrator

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Read-ConfigYaml {
    param([string]$Path)
    $result = @{}
    if (-not (Test-Path $Path)) { return $result }
    Get-Content $Path -Encoding UTF8 | ForEach-Object {
        if ($_ -match '^\s*([A-Za-z0-9_]+)\s*:\s*"?([^"#]*)"?\s*(?:#.*)?$') {
            $k = $matches[1].Trim(); $v = $matches[2].Trim()
            if ($k -ne '' -and $v -ne '') { $result[$k] = $v }
        }
    }
    return $result
}

function Write-Pass { param([string]$Msg) Write-Host "  [PASS] $Msg" -ForegroundColor Green }
function Write-Fail { param([string]$Msg) Write-Host "  [FAIL] $Msg" -ForegroundColor Red }
function Write-Warn { param([string]$Msg) Write-Host "  [WARN] $Msg" -ForegroundColor Yellow }
function Write-Info { param([string]$Msg) Write-Host "        $Msg" -ForegroundColor Gray }
function Write-Fix  { param([string]$Msg) Write-Host "  >  $Msg"   -ForegroundColor Cyan }

$overallPass = $true

# ---------------------------------------------------------------------------
# Read config.yaml
# ---------------------------------------------------------------------------
$configPath = Join-Path $PSScriptRoot 'config.yaml'
if (-not (Test-Path $configPath)) {
    Write-Host ''
    Write-Host 'ERROR: config.yaml not found.' -ForegroundColor Red
    Write-Host '  Copy config.template.yaml -> config.yaml and fill in your values.'
    exit 1
}

$c = Read-ConfigYaml -Path $configPath

$subscriptionId = $c['subscription_id']
$resourceGroup  = if ($c.ContainsKey('resource_group')) { $c['resource_group'] } else { '' }
$envName        = if ($c.ContainsKey('env_name'))       { $c['env_name'] }       else { '' }

if (-not $subscriptionId) {
    Write-Host "ERROR: 'subscription_id' is missing from config.yaml." -ForegroundColor Red
    exit 1
}

Write-Host ''
Write-Host '=== AIO Pre-flight Permission Check ===' -ForegroundColor Cyan
Write-Host "  Subscription  : $subscriptionId"
Write-Host "  Resource Group: $(if ($resourceGroup) { $resourceGroup } else { '(auto-generated by azd)' })"
Write-Host "  Env name      : $(if ($envName) { $envName } else { '(not set)' })"
Write-Host ''

# ---------------------------------------------------------------------------
# Check 1: az login
# ---------------------------------------------------------------------------
Write-Host '--- Check 1: Azure CLI login ---'
$oid = $null
try {
    $accountJson = az account show --subscription $subscriptionId -o json 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $accountJson) { throw 'no account' }
    $account = $accountJson | ConvertFrom-Json
    $oid     = az ad signed-in-user show --query id -o tsv 2>$null
    if (-not $oid) { throw 'no oid' }
    Write-Pass "Signed in as: $($account.user.name)  (OID: $oid)"
    Write-Pass "Subscription: $($account.name) [$subscriptionId]"
} catch {
    Write-Fail 'Not logged in to Azure CLI or subscription not found.'
    Write-Fix  'az login'
    Write-Fix  "az account set --subscription $subscriptionId"
    exit 1
}
Write-Host ''

# ---------------------------------------------------------------------------
# Gather all role assignments once (sub scope + RG scope if RG exists)
# ---------------------------------------------------------------------------
$subScope = "/subscriptions/$subscriptionId"

Write-Info 'Fetching role assignments at subscription scope...'
$subAssignments = @()
try {
    $json = az role assignment list --assignee $oid --scope $subScope --subscription $subscriptionId -o json 2>$null
    if ($LASTEXITCODE -eq 0 -and $json) { $subAssignments = $json | ConvertFrom-Json }
} catch {}

$rgAssignments = @()
if ($resourceGroup -ne '') {
    $rgExists = (az group exists --name $resourceGroup --subscription $subscriptionId 2>$null) -eq 'true'
    if ($rgExists) {
        Write-Info "Fetching role assignments at resource group scope ($resourceGroup)..."
        try {
            $rgScope = "$subScope/resourceGroups/$resourceGroup"
            $json = az role assignment list --assignee $oid --scope $rgScope --subscription $subscriptionId -o json 2>$null
            if ($LASTEXITCODE -eq 0 -and $json) { $rgAssignments = $json | ConvertFrom-Json }
        } catch {}
    } else {
        Write-Info "Resource group '$resourceGroup' does not exist yet - checking sub scope only."
    }
}

$allAssignments = @($subAssignments) + @($rgAssignments)

function Has-Role {
    param([string]$RoleId)
    foreach ($a in $allAssignments) {
        if ((Split-Path $a.roleDefinitionId -Leaf) -eq $RoleId) { return $true }
    }
    return $false
}

$hasOwner     = Has-Role $OwnerId
$hasContrib   = $hasOwner -or (Has-Role $ContribId)
$hasRbacAdmin = $hasOwner -or (Has-Role $RbacAdminId)

Write-Host ''

# ---------------------------------------------------------------------------
# Check 2: Contributor (resource creation)
# ---------------------------------------------------------------------------
Write-Host '--- Check 2: Contributor role (required to create Azure resources) ---'
Write-Info 'Needed to provision: VNet, VM, Key Vault, Storage, ACR, Schema Registry'

if ($hasContrib) {
    $label = if ($hasOwner) { 'Owner' } else { 'Contributor' }
    Write-Pass "Has '$label' - resource creation permission confirmed."
} else {
    Write-Fail "Missing 'Contributor' (or 'Owner') on this subscription or resource group."
    Write-Host ''
    Write-Host '  This role lets the deployer create all Azure resources in the Bicep template.' -ForegroundColor Yellow
    Write-Host '  Ask your subscription admin to grant it at resource group scope:' -ForegroundColor Yellow
    Write-Fix  "az role assignment create --assignee $oid --role Contributor --scope $subScope/resourceGroups/$resourceGroup"
    Write-Host ''
    $overallPass = $false
}
Write-Host ''

# ---------------------------------------------------------------------------
# Check 3: Role Based Access Control Administrator (role assignment write)
# ---------------------------------------------------------------------------
Write-Host '--- Check 3: Role Based Access Control Administrator ---'
Write-Info 'Required because roleAssignments.bicep creates these 4 assignments at provision time:'
Write-Info '  Key Vault Secrets User        -> AIO managed identity  (on Key Vault)'
Write-Info '  Key Vault Secrets Officer     -> deploying user         (on Key Vault)'
Write-Info '  Storage Blob Data Contributor -> schema registry        (on Storage Account)'
Write-Info '  AcrPull                       -> VM system identity     (on Container Registry)'

if ($hasRbacAdmin) {
    $label = if ($hasOwner) { 'Owner' } else { 'Role Based Access Control Administrator' }
    Write-Pass "Has '$label' - role assignment write permission confirmed."
} else {
    Write-Fail "Missing 'Role Based Access Control Administrator' (or 'Owner') on this subscription or resource group."
    Write-Host ''
    Write-Host '  This role grants only the ability to manage role assignments.' -ForegroundColor Yellow
    Write-Host '  It does NOT grant broad resource access like Owner does.' -ForegroundColor Gray
    Write-Host '  Ask your subscription admin to grant it at resource group scope:' -ForegroundColor Yellow
    Write-Fix  "az role assignment create --assignee $oid --role 'Role Based Access Control Administrator' --scope $subScope/resourceGroups/$resourceGroup"
    Write-Host ''
    $overallPass = $false
}
Write-Host ''

# ---------------------------------------------------------------------------
# Check 4: Soft-deleted Key Vaults with the same env-name prefix
# ---------------------------------------------------------------------------
Write-Host '--- Check 4: Soft-deleted Key Vault conflicts ---'
Write-Info 'Querying deleted Key Vaults (this may take a few seconds)...'

try {
    $deletedJson = az keyvault list-deleted --subscription $subscriptionId -o json 2>$null
    $deletedVaults = if ($deletedJson) { $deletedJson | ConvertFrom-Json } else { @() }

    if ($deletedVaults -and $deletedVaults.Count -gt 0) {
        $prefix = if ($envName) { "kv-$($envName.ToLower() -replace '[^a-z0-9]','-')" } else { 'kv-aio' }
        $conflicts = $deletedVaults | Where-Object { $_.name -like "$prefix*" }

        if ($conflicts) {
            foreach ($v in $conflicts) {
                $kvLoc = $v.properties.location
                Write-Fail "Soft-deleted Key Vault found: '$($v.name)' (location: $kvLoc)"
                Write-Info '  Purge it to free the globally-unique name before deploying:'
                Write-Fix  "az keyvault purge --name $($v.name) --location $kvLoc --subscription $subscriptionId"
            }
            Write-Host ''
            Write-Host '  Key Vault names are globally unique and held during soft-delete (90 days).' -ForegroundColor Yellow
            Write-Host '  Provisioning fails with VaultAlreadyExists until the old vault is purged.' -ForegroundColor Yellow
            Write-Host '  Warning: purge permanently deletes the vault and ALL its secrets.' -ForegroundColor Yellow
            $overallPass = $false
        } else {
            Write-Pass "No soft-deleted Key Vaults matching prefix '$prefix' found."
        }
    } else {
        Write-Pass 'No soft-deleted Key Vaults in this subscription.'
    }
} catch {
    Write-Warn "Could not query deleted Key Vaults: $($_.Exception.Message)"
    Write-Info  "Manually verify: az keyvault list-deleted --subscription $subscriptionId"
}
Write-Host ''

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
if ($overallPass) {
    Write-Host '=== All checks passed. You are ready to run: .\Deploy.ps1 ===' -ForegroundColor Green
    exit 0
} else {
    Write-Host '=== One or more checks FAILED. Resolve the issues above then re-run this script. ===' -ForegroundColor Red
    exit 1
}
